# Generated by Django 4.2.3 on 2024-02-11 02:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=11, message='Informe um CPF válido.')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator('Informe um endereço de e-mail válido.')])),
                ('phone', models.CharField(max_length=15)),
                ('specialty', models.CharField(max_length=50)),
                ('crn', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('nutritionist', 'Nutritionist'), ('patient', 'Patient')], default='nutritionist', max_length=20)),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=6, message='A senha deve ter pelo menos 6 caracteres.')])),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
