# Generated by Django 4.2.3 on 2024-03-30 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=11, message='Enter a valid CPF.')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator('Enter a valid email address.')])),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('specialty', models.CharField(max_length=50)),
                ('crn', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=6, message='Password must be at least 6 characters.')])),
            ],
            options={
                'verbose_name': 'Nutritionist',
                'verbose_name_plural': 'Nutritionists',
            },
        ),
    ]
