# Generated by Django 4.2.3 on 2024-02-15 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('date_Consulta', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('address_consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='locations.address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('user_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
        migrations.CreateModel(
            name='ConsultationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_history', to='consultation.consultation')),
                ('user_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ConsultationHistory',
                'verbose_name_plural': 'ConsultationHistories',
            },
        ),
    ]
