# Generated by Django 4.2.3 on 2024-04-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultation_address_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_Consulta',
            field=models.DateTimeField(null=True),
        ),
    ]
