# Generated by Django 4.2.3 on 2024-04-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_alter_consultation_date_consulta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultationHistory',
        ),
    ]
