# Generated by Django 4.2.3 on 2024-02-14 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientConsultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsultation',
            name='descrition',
        ),
    ]
