# Generated by Django 4.2.3 on 2024-03-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='nutritionist',
        ),
    ]
