# Generated by Django 4.2.3 on 2024-04-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_mealplan_meal_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(verbose_name='Time Value'),
        ),
    ]
