# Generated by Django 4.2.3 on 2024-04-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
