# Generated by Django 4.2.3 on 2024-03-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutritionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageClini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageClini_nutritionist', to='nutritionist.nutritionist')),
            ],
            options={
                'verbose_name': 'MessageClini',
                'verbose_name_plural': 'MessageClinis',
            },
        ),
    ]
