# Generated by Django 4.2.3 on 2024-03-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageClini', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageclini',
            old_name='user',
            new_name='nutritionist',
        ),
    ]
