# Generated by Django 4.2.3 on 2024-03-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutritionist', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_value', models.TimeField(verbose_name='Time Value')),
            ],
            options={
                'verbose_name': 'TimeSchedule',
                'verbose_name_plural': 'TimeSchedules',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointments', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_nutritionist', to='nutritionist.nutritionist')),
                ('schedules', models.ManyToManyField(blank=True, related_name='appointments', to='appointments.timeschedules', verbose_name='Schedules')),
                ('service_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='locations.address')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
