# Generated by Django 4.2.3 on 2024-02-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedules',
            field=models.ManyToManyField(related_name='appointments', to='appointments.timeschedules', verbose_name='timeSchedules'),
        ),
    ]
