# Generated by Django 4.2.3 on 2024-02-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='appointments.timeschedules', verbose_name='Schedules'),
        ),
    ]
