# Generated by Django 4.2.3 on 2024-04-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_timeschedules_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='appointments.timeschedules', verbose_name='TimeSchedules'),
        ),
    ]
