# Generated by Django 4.2.3 on 2024-04-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_appointments',
            field=models.DateField(unique=True),
        ),
    ]
